### ISSUE TITLE
真实场景遇到的一些问题

### ISSUE THREAD

**Issue by dengzhiguiios** [youlookwhat/BySMB#2]
这里提几个遇到的点:
1.作者对外开放的方法只能通过读取本地的文件流 , 然后再通过smb写入pc端 . 对于我的场景 , 是直接能拿到写入的字符串内容 , 不需要读取本地文件流再写入pc端 .
2.对于共享文件夹名的支持不友好 , 假如是"ShareFile"为共享文件名是可以的 , 但是"ShareFile/K1"这样带有斜杠的就直接报错 . 看了源码 , SmbPath类的另外一个构造方法是有path字段的 , 但是并没有对外开放.
`
val bySmb = BySMB.with().setConfig(ip,       // ip
                        computerSharingUserName, // 用户名 
                        computerSharingPassword, // 密码 
                        printPath // 共享文件夹名 
                    ).setReadTimeOut(60).setSoTimeOut(180).build() 
`
以上只是提出我的使用场景遇到的问题 , 还是感谢作者开放源码 , 可以省了不少事 .

**Comment by youlookwhat** [comment]
为什么关了呢，已经找到解决方案了吗
