### ISSUE TITLE
有java版的吗

### ISSUE THREAD

**Issue by chengzhuangjie** [youlookwhat/BySMB#4]

**Comment by youlookwhat** [comment]
暂时没有哈，需要的我可以写一份

**Comment by zhao1597455971** [comment]
我也需要Java的 幸亏大佬写一份 感谢

**Comment by youlookwhat** [comment]
已给出java版本demo，详见：[BySMBJavaActivity.java](https://github.com/youlookwhat/BySMB/blob/main/app/src/main/java/me/jingbin/smb/demo/BySMBJavaActivity.java)

需要移入：`implementation 'com.github.youlookwhat:BySMB:1.2.5'`

**Comment by youlookwhat** [comment]
@chengzhuangjie @zhao1597455971
